version: '3.9'
services:
  mongodb:
    image: mongo:7.0
    container_name: my-mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
    #  MONGO_INITDB_ROOT_USERNAME: admin
   #   MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: mongodatabase
  #    MONGO_INITDB_SCRIPT: /docker-entrypoint-initdb.d/init-mongo.js